### PR TITLE
clonetree: stub: fix nonlinux builds

### PR DESCRIPTION
**Pull request by fromanirh**
Fix the builds removing leftover imprts, and mark actually specific linux test as so.

The existing clonetree tests are linux specific because  they weere developed on linux.
While no intentional restriction on linux was put in, no real thought to other OSes was put in either.

So we just make the expectations explicit and we mark these tests as linux specific until we have the chance to truly generalize them.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
now the darwin lane is green. We do little in this lane, but this is the best we can do atm. :\

**Comment by fromanirh** [comment]
Same goes for the windows lane. Most tests disabled. I guess is the best we can do with so limited platform availability

**Comment by fromanirh** [comment]
Once this is merged, we can also merge https://github.com/jaypipes/ghw/pull/262

**Review by jaypipes — APPROVED** [review]
Thanks Francesco! :)

**Pull request merged**
