### PR TITLE
add docs for Label and FilesystemLabel in README

### PR DESCRIPTION
**Pull request by jaypipes**
Adds missing documentation for new Label and FilesystemLabel fields for
Partition structs.

Signed-off-by: Jay Pipes <jaypipes@gmail.com>

### CODE REVIEW

**Comment by jaypipes** [comment]
@Itxaka please take a look :)

**Comment by Itxaka** [comment]
ouch, sorry about that! and thanks for fixing it!

**Comment by fromanirh** [comment]
LGTM. IIUC @Itxaka is happy as well? if so I can merge!

**Comment by Itxaka** [comment]
Lgtm

**Review by fromanirh — APPROVED** [review]

**Comment by jaypipes** [comment]
> ouch, sorry about that! and thanks for fixing it!

LOL, no worries! :)

**Pull request merged**
