### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by taigrr**
Link to COC broke at one point.

### CODE REVIEW

**Comment by taigrr** [comment]
I just realized I forked off my main, not yours. I can fix this, or you can, I'll wait to hear back.

**Comment by jaypipes** [comment]
> I just realized I forked off my main, not yours. I can fix this, or you can, I'll wait to hear back.

@taigrr yes, please do rebase from `github.com:jaypipes/main` :) thank you!

**Comment by fromanirh** [comment]
thanks! we can merge the moment it's rebased on top of `main`.

**Comment by taigrr** [comment]
Thanks, done

**Review by jaypipes — APPROVED** [review]
:+1: thanks!

**Pull request merged**
