### PR TITLE
differentiate drive type and storage controller

### PR DESCRIPTION
**Pull request by jaypipes**
This patch attempts to bring some clarity to the block device module's
`ghw.Disk` struct with regards to the storage controller and drive type.
We add a new enumeration of drive types to `ghw`:

* DRIVE_TYPE_HDD - hard disk drive
* DRIVE_TYPE_FDD - floppy disk drive
* DRIVE_TYPE_ODD - optical disk drive
* DRIVE_TYPE_SSD - solid-state drive

Along with a new `ghw.StorageController` enumeration which describes the
controller/driver used for translating block reads/writes to the
underlying hardware, which the following enum values:

* STORAGE_CONTROLLER_IDE - integrated device electronics
* STORAGE_CONTROLLER_SCSI - small computer system interface
* STORAGE_CONTROLLER_NVME - non-volatile memory express
* STORAGE_CONTROLLER_VIRTIO - libvirt/virtio storage driver

The `ghw.Disk.BusType` field is deprecated and no longer serialized into
JSON/YAML output.

Issue #117

### CODE REVIEW

**Comment by jpo-joyent** [comment]
There exist a number of distinct optical media: CD, DVD, Blu-ray, etc. and the read-only/RW variants of each. Is it interesting (or possible) to differentiate those as well?

Doesn't matter for my use case, but figured I'd mention it from an interface design perspective.

**Comment by jaypipes** [comment]
> There exist a number of distinct optical media types: CD, DVD, Blu-ray, etc. and the read-only/RW variants of each. Is it interesting (or possible) to differentiate those as well?

Possibly in the future. Not for this particular PR, though. Right now, I'm just concerned about fixing ghw 0.3 for Mac users (!) and getting accurate descriptive fields on the Disk struct. Do you think this PR accomplishes that?

> Doesn't matter for my use case, but figured I'd mention it from an interface design perspective.

Ack, will look into adding something for that in a future release.

Best,
-jay

**Comment by jpo-joyent** [comment]
> Right now, I'm just concerned about fixing ghw 0.3 for Mac users (!) and getting accurate descriptive fields on the Disk struct. Do you think this PR accomplishes that?

Well, except for...

```
$ go build ./cmd/ghwc
# github.com/jaypipes/ghw
./block_darwin.go:255:28: undefined: driveTypeFromPlist
./block_darwin.go:256:28: undefined: storageControllerFromPlist
./block_darwin.go:257:28: undefined: busTypeFromPlist
```

(see proposed in fix) https://github.com/jaypipes/ghw/pull/120

Probably :)

**Comment by jaypipes** [comment]
Yeah, I gotta get the CI for Mac going :( thanks @jpo-joyent (again!) :)

**Comment by jaypipes** [comment]
Well, on my Macbook, I now get this:

```
$ go run cmd/ghwc/main.go block
block storage (2 disks, 932GB physical storage)
 /dev/disk0 SSD (466GB) NVMe [@/PCI0@0/RP17@1B/SSD0@0/IONVMeController] vendor=Apple model=APPLE SSD SM0512L serial=C02745600E7J1J71A WWN=
  /dev/disk0s1 (300MB) [EFI]
  /dev/disk0s2 (466GB) [Apple_APFS]
 /dev/disk1 SSD (466GB) NVMe [@/PCI0@0/RP17@1B/SSD0@0/IONVMeController] vendor=Apple model=APPLE SSD SM0512L serial=C02745600E7J1J71A WWN=
  /dev/disk1s1 (466GB) [APFS Volume] mounted@/
  /dev/disk1s2 (466GB) [APFS Volume]
  /dev/disk1s3 (466GB) [APFS Volume] mounted@/Volumes/Recovery
  /dev/disk1s4 (466GB) [APFS Volume] mounted@/private/var/vm
```

so at least we know that something is kind of working for Macs with this PR...

**Pull request merged**
