### PR TITLE
Add DMI information as top-level XXXInfo structs

### LINKED ISSUE #96: Grab baseboard info
Need some baseboard info, like in `dmidecode --type baseboard` output:
```
	...
	Manufacturer: ASUSTeK COMPUTER INC.
	Product Name: B150M-C
	Version: Rev X.0x
	Serial Number: 160368165300404
	Asset Tag: Default string
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: Default string
	Chassis Handle: 0x0003
	Type: Motherboard
	Contained Object Handles: 0
	...
```

### LINKED ISSUE #108: Consider retrieving privileged device/system information
One of the design constraints of `ghw` is that we retrieve information that unprivileged users can retrieve and do not attempt to retrieve information from superuser-restricted areas (like `/sys/firmware/dmi/tables/DMI` on Linux for example).

There have been a number of requests, however, to have `ghw` dig for privileged information about baseboard information (Issue #96), certain firmware, hardware RAID controller information (Issue #94), and certain information that is only available to root/privileged users.

Consider relaxing the design constraint about unprivileged operations and attempt to retrieve information from privileged locations, but always fall back on a safe operation that doesn't return errors to the user, instead simply emitting warnings and setting requested information to some empty default values.

### PR DESCRIPTION
**Pull request by jaypipes**
Adds BIOS, chassis, baseboard and product information as top-level `XXXInfo` structs to `ghw`.

Extends #140 and addresses the comments I raised in that review.

Closes #96 
Closes #108

### CODE REVIEW

**Comment by jaypipes** [comment]
@mnaser please take a look at this and test it out if you have some free time. It builds on top of your original PR (#140) but uses separate top-level structs instead of a single DMIInfo struct with nested elements.

**Comment by mnaser** [comment]
So with the changes implemented here, they are working with no problem.

https://github.com/vexxhost/node-labeler/commit/d4fa55ef0f004e2a648af6fada74cdd6c05a64d8

Once the next release is out, we can totally pin to the released version :)

**Comment by mnaser** [comment]
(in other words: it works perfect for me!)

**Comment by jaypipes** [comment]
> (in other words: it works perfect for me!)

Awesome, so glad to hear! BTW, I'll be cutting a new release v0.5.0 today which will be properly semver'd, you can then add a proper github.com/jaypipes/ghw@v0.5.0 tag to your go.mod and remove the `v0.0.0-20191127163616-59d4527537a4` go mod pseudoversion. :)

**Comment by jaypipes** [comment]
@mnaser OK, release v0.5.0 is cut: https://github.com/jaypipes/ghw/releases/tag/v0.5.0

**Comment by mnaser** [comment]
Cool.  I just pushed v0.1.1 which uses the actual tagged release and it seems to be working just fine!

Thanks and sorry for that delay on my side @jaypipes

**Comment by jaypipes** [comment]
> Cool.  I just pushed v0.1.1 which uses the actual tagged release and it seems to be working just fine!

Excellent news.

> Thanks and sorry for that delay on my side @jaypipes

No need to apologize at all! :)

**Pull request merged**
