### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by glimchb**
### Authors

Co-authored by: Xingyou Chen [rockrush@rockwork.org](mailto:rockrush@rockwork.org)

### Details

- collected snapshot data from my EC2 aarch64 instance
- Add new const for `/sys/devices/system/cpu`
- Cherry-picked #303 
- Fixed review comments
- added tests based on ARM snapshot

### Tests

tested on 8 core machine:
```
$ uname -m
aarch64

$ go run cmd/ghwc/main.go cpu
cpu (1 physical package, 8 cores, 8 hardware threads)
 physical package #36 (8 cores, 8 hardware threads)
  processor core #0 (1 threads), logical processors [0]
  processor core #1 (1 threads), logical processors [1]
  processor core #2 (1 threads), logical processors [2]
  processor core #3 (1 threads), logical processors [3]
  processor core #4 (1 threads), logical processors [4]
  processor core #5 (1 threads), logical processors [5]
  processor core #6 (1 threads), logical processors [6]
  processor core #7 (1 threads), logical processors [7]
  capabilities: [sha1 sha2 crc32 cpuid
```

### CODE REVIEW

**Comment by glimchb** [comment]
@ffromani this could help with #199 and #303

**Comment by ffromani** [comment]
@jaypipes sure thing! I'll have a look and comment here ASAP. Thanks @glimchb to offer this

**Comment by jaypipes** [comment]
> @jaypipes sure thing! I'll have a look and comment here ASAP. Thanks @glimchb to offer this

@ffromani grazie mille!

**Comment by glimchb** [comment]
@jaypipes the CPU tests will fail until we merged #303 WDYT ? we can add other tests...

**Comment by jaypipes** [comment]
> @jaypipes the CPU tests will fail until we merged #303 WDYT ? we can add other tests...

It's a shame that @rockrush did not want to respond to our PR review comments on that one. @glimchb what do you think about creating a PR that combines your snapshot addition with #303, addresses the PR reviews, and adds some simple unit tests for AARCH64 platforms?

**Comment by glimchb** [comment]
> @glimchb what do you think about creating a PR that combines your snapshot addition with #303, addresses the PR reviews, and adds some simple unit tests for AARCH64 platforms?

Sure, I can do that for sure if we agree on the strategy - snapshot vs qemu or both...

**Comment by glimchb** [comment]
@ffromani not sure we can use QEMU for our use acse due to https://github.com/actions/runner-images/issues/183 
I'm using a lot of qemu for multi platform docker builds but we need arm kernel not just instruction set emulation to see `lscpu` and `/proc/cpuinfo` correctly...

**Comment by glimchb** [comment]
@jaypipes @ffromani address all comments and broke to smaller commits, please review

**Review by jaypipes — CHANGES_REQUESTED** [review]
This is looking much better, thank you @glimchb!

One more suggestion inline for you. Also, if you might edit your PR summary and put the following in there:

```
Co-authored by: Xingyou Chen [rockrush@rockwork.org](mailto:rockrush@rockwork.org)
```

I'm sure @rockrush would appreciate that!

Best,
-jay

**Comment by glimchb** [comment]
> One more suggestion inline for you. Also, if you might edit your PR summary and put the following in there:
> I'm sure @rockrush would appreciate that!

Absolutely. Done, thanks for suggestion. 
The commit https://github.com/jaypipes/ghw/pull/333/commits/34f45f4cfdb628931eb1732fa414a7ae97191354 was cherry-picked, so it has proper `Signed-off-by: Xingyou Chen <rockrush@rockwork.org>`
But as you suggested, also added this to PR description

**Review by jaypipes — APPROVED** [review]
Wonderful, thank you so much @glimchb for your very timely PR and tests! :)

**Pull request merged**
