### PR TITLE
net_linux : Add detection to know if nic is on PCI BUS

### PR DESCRIPTION
**Pull request by mikefaille**
I need it to find physical interface on my server; especially ones on PCI BUS
If nic is on pci bus, print nic according this info
Update documentation according nic pci detection

### CODE REVIEW

**Comment by pwFoo** [comment]
Dectect NIC to initialize network after booting a minimal system would be great!
Would need it not only for PCI devices.

**Comment by mikefaille** [comment]
@pwFoo Maybe, we can detect virtual devices more easily using something like :  

```
ls /sys/class/net -l | grep devices/virtual/net/
lrwxrwxrwx 1 root root 0 déc 15 11:02 br-0a5a2e80b26b -> ../../devices/virtual/net/br-0a5a2e80b26b
lrwxrwxrwx 1 root root 0 déc 15 11:02 br-6847a3df4828 -> ../../devices/virtual/net/br-6847a3df4828
lrwxrwxrwx 1 root root 0 déc 15 11:02 br-a9a72a125b03 -> ../../devices/virtual/net/br-a9a72a125b03
lrwxrwxrwx 1 root root 0 déc 15 11:02 docker0 -> ../../devices/virtual/net/docker0
lrwxrwxrwx 1 root root 0 déc 15 11:02 docker_gwbridge -> ../../devices/virtual/net/docker_gwbridge
lrwxrwxrwx 1 root root 0 déc 15 11:02 lo -> ../../devices/virtual/net/lo
lrwxrwxrwx 1 root root 0 déc 15 11:02 veth2be86f9 -> ../../devices/virtual/net/veth2be86f9
lrwxrwxrwx 1 root root 0 déc 15 11:02 virbr0 -> ../../devices/virtual/net/virbr0
lrwxrwxrwx 1 root root 0 déc 15 11:02 virbr0-nic -> ../../devices/virtual/net/virbr0-nic
```

By excluding virtual interfaces (ones from previous list), we can always find physical nic (I think ). 

The trouble here is there is a conflict about `virtual` definition on actual code. 
https://github.com/jaypipes/ghw/blob/master/net_linux.go#L62
Here, we define `virtio` nic as `virtual` ones.

My suggestion then is creating a new major release that break previous behaviour : I think IsVirtual() must be true for NIC giving `true` when their symlink from `ls -l /sys/class/net/*` contain ` devices/virtual/net/`

**Comment by jaypipes** [comment]
> My suggestion then is creating a new major release that break previous behaviour : I think IsVirtual() must be true for NIC giving `true` when their symlink from `ls -l /sys/class/net/*` contain ` devices/virtual/net/`

I would support changing the code that determines if a NIC is virtual. I do not support, however, the code that is in this patch at the moment, that looks for "pci" in the device path and adds another boolean field to the `NIC` struct.

@mikefaille I'm a little unsure what your end goal is here. Perhaps you could elaborate? Are you just looking for the low-level hardware (or software, in the case of virtual NICs) bus that handles the NIC? Or are you running into a problem where (as @pwFoo mentions), a virtual NIC is mistakenly being reported as a non-virtual NIC because the code that determines "virtual-ness" is looking for the wrong thing in the device path?

**Comment by jaypipes** [comment]
> I can implement that if it's ok. It will works for me.

Are you asking if you can change the implementation of the IsVirtual() function? Yes, that would be fine.

**Comment by mikefaille** [comment]
> > I can implement that if it's ok. It will works for me.
> 
> Are you asking if you can change the implementation of the IsVirtual() function? Yes, that would be fine.

Sharp, I'll do it !

**Comment by mikefaille** [comment]
I close this actual pull request in favour of this one : https://github.com/jaypipes/ghw/pull/100

**Pull request closed without merging**
